config/routes.rb
Rails.application.routes.draw do
  resources :tags
  #resources :todos
      # /goals/:goal_id/todos/:id/sort というURLに対して
      # todos#sort というアクションを割り当てる
  resources :goals do
    resources :todos do
      member do
        get "sort"
      end
    end
  end

      
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :todos, -> { order("done ASC, position ASC").includes(:goal) }, dependent: :destroy
  validates :title, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :goal
  has_many :todo_tags
  has_many :tags, through: :todo_tags
  accepts_nested_attributes_for :todo_tags

  acts_as_list scope: [:goal_id]
 
  validates :position, numericality: { only_integer: true, allow_nil: true }
  validates :content, presence: true
  validates :done, inclusion: { in: [true, false] }
 
  after_initialize :set_default, if: :new_record?
 
  private
 
  def set_default
    self.done = false if self.done.blank?
  end

end

app/models/todo_tag.rb
class TodoTag < ApplicationRecord
  belongs_to :todo
  belongs_to :tag

  validates :todo_id, :uniqueness => { :scope => :tag_id }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :goals
  has_many :tags
  
  def available_tags
    self.tags.select(&:persisted?)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  def index
    #@goals = Goal.all
    @goals = current_user.goals.all

  end

  # GET /goals/1
  #def show
  #end

  # GET /goals/new
  def new
    #@goal = Goal.new
    @goal = current_user.goals.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  def create
    #@goal = Goal.new(goal_params)
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      #redirect_to @goal, notice: 'Goal was successfully created.'
      @status = true

    else
      #render :new
      @status = false
    end
  end

  # PATCH/PUT /goals/1
  def update
    if @goal.update(goal_params)
      #redirect_to @goal, notice: 'Goal was successfully updated.'
      @status = true

    else
      #render :edit
      @status = false

    end
  end

  # DELETE /goals/1
  def destroy
    @goal.destroy
    #redirect_to goals_url, notice: 'Goal was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      #@goal = Goal.find(params[:id])
      @goal = current_user.goals.find_by(id: params[:id])
      redirect_to(goals_url, alert: "ERROR!!") if @goal.blank?
    end

    # Only allow a trusted parameter "white list" through.
    def goal_params
      params.require(:goal).permit(:title, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to goals_path if user_signed_in?
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name, :user_id)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal
  #before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :sort]

  # GET /todos
  # def index
  #   @todos = Todo.all
  # end

  # # GET /todos/1
  # def show
  # end

  # GET /todos/new
  def new
    # @todo = Todo.new
    #@goalに紐付いたtodosをnewしています
    @todo = @goal.todos.new
  end
  def sort
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  def create
    #@todo = Todo.new(todo_params)
    @todo = @goal.todos.new(todo_params)

    if @todo.save
      # redirect_to @todo, notice: 'Todo was successfully created.'
      @status = true
    else
      # render :new
      @status = false
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
      #redirect_to @todo, notice: 'Todo was successfully updated.
      @status = true
    else
      # render :edit
      @status = false
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    # redirect_to todos_url, notice: 'Todo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = current_user.goals.find_by(id: params[:goal_id])
      redirect_to(goals_url, alert: "ERROR!!") if @goal.blank?
    end

    def set_todo
      # @todo = Todo.find(params[:id])
      @todo = @goal.todos.find_by(id: params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    # def todo_params
    #   params.require(:todo).permit(:content, :goal_id, :position, :done)
    # end
    def todo_params
      params.require(:todo).permit(:content, :goal_id, :position, :done, tag_ids: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def bs4_bgcolor_for(flash_key)
      case flash_key
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        flash_key.to_s
      end
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/goals/_form.html.erb
<div class="modal fade" id="goalModal" tabindex="-1" role="dialog" aria-labelledby="goalModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: goal, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="goalModal"><%= "#{params[:action].camelize} #{goal.model_name.human}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if goal.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>
              <ul>
                <% goal.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title %>
          </div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/_goal.html.erb
<div class="card bg-light d-inline-block text-wrap h-100 mx-1 goal-card"
  data-model_name="<%= Goal.model_name.singular %>"
  data-id="<%= goal.id %>">
  <div class="d-flex flex-column h-100" style="width: 25rem; min-width: 25rem;">
    <div class="font-weight-bold px-4 py-2 goal-header">
      <div class="pr-5">
        <%= goal.title %>
      </div>
      <div class="text-right position-absolute" style="top: 4px; right: 4px">
        <%= link_to(new_goal_todo_path(goal), title: "New TODO", class: "btn px-0", remote: true) do %><i class="fas fa-plus align-middle"></i><% end %>
        <div class="btn-group">
          <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v align-middle"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right text-middle">
            <%= link_to "Edit", edit_goal_path(goal), class: "dropdown-item", remote: true %>
            <%= link_to "Delete", goal, method: :delete, class: "dropdown-item text-danger", remote: true, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body px-2 pb-2 pt-0 overflow-auto todo-cards">
      <%= render partial: "todos/todo", collection: goal.todos, as: :todo %>
    </div>
  </div>
</div>

app/views/goals/create.js.erb
// modalを閉じる処理
$("#goalModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();


// Rails @status => true 画面の書き換え : false モーダルを再度表示
<% if @status %>
$("#goalsIndex").append("<%= j(render @goal) %>");

<% else %>
$("#modalArea").html("<%= j(render 'goals/form', goal: @goal) %>")
$("#modalArea").find(".modal").modal('show')
<% end %>

app/views/goals/destroy.js.erb
// modalを閉じる処理
$("#goalModal").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

// 画面の書き換え
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').remove();

app/views/goals/edit.js.erb
// モーダル追加
$("#modalArea").html(
  "<%= j(render 'form', goal: @goal) %>"
);

// フォームにフォーカス
//modalAreaのなかから modalを探してきて、
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
  $("#modalArea").find("form input[type=text]")[0].focus();
})

// モーダル表示
$("#modalArea").find(".modal").modal("show");

app/views/goals/index.html.erb
<div class="goal-title-area px-3">
  <h1>Goals</h1>
  <%= link_to new_goal_path, class: "btn p-0 text-dark pr-5", remote: true do %>
    <i class="fas fa-plus align-middle pr-1"></i><span class="align-middle">Create A New Goal</span>
  <% end %>
  <%= link_to new_tag_path, class: "btn p-0 text-dark", remote: true do %>
    <i class="fas fa-plus align-middle pr-1"></i><span class="align-middle">Manage Tag</span>
  <% end %>

</div>
<div class="pt-3 p-1 text-nowrap goal-index-area" id="goalsIndex">
  <%= render @goals %>
</div>

app/views/goals/new.js.erb
$("#modalArea").html("<%= j(render 'form', goal: @goal) %>")

// フォームにフォーカス
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})

$("#modalArea").find(".modal").modal('show')

app/views/goals/update.js.erb
// モーダルを閉じる処理
$("#goalModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();


// Rails @status => true 画面の書き換え : false モーダルを再度表示
<% if @status %>
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').replaceWith("<%= j(render @goal) %>");

<% else %>
$("#modalArea").html("<%= j(render 'form', goal: @goal) %>")
$("#modalArea").find(".modal").modal('show')
<% end %>

app/views/home/index.html.erb
<h1 class="display-1 text-white text-center font-weight-bold" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">TODO App</h1>
<h2 class="text-center" style="color: #ccc">TODOリストを作ろう。</h2>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light d-flex flex-column justify-content-end align-items-end">
  <div class="text-muted small px-3">TODO App by Ruby on Rails & Bootstrap 4</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'TODO App', root_path, class: "navbar-brand" %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <%  if user_signed_in?  %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <div id="modalArea"></div>
      <main>
        <div class="container-fruid h-100 p-2 d-flex flex-column">
          <%= yield %>
        </div>
      </main>
      <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/tags/_edit_form.html.erb
<div class="modal fade" id="tagModal" tabindex="-1" role="dialog" aria-labelledby="tagModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: tag, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="tagModal"><%= "#{params[:action].camelize} #{tag.model_name.human}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if tag.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
              <ul>
                <% tag.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name %>
          </div>
        </div>
        <div class="modal-footer actions">
          <%= link_to new_tag_path, remote: true do %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <% end %>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/_focus_modal.js.erb
// フォームにフォーカス
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
  $("#modalArea").find("form input[type=text]").focus();
})

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_index.html.erb
<div id="tagIndex">
  <%= render partial: "tags/tag", collection: current_user.tags.select(&:persisted?), as: :tag %>
</div>

app/views/tags/_remove_modal.js.erb
// モーダルを閉じる処理
// <%= element ||= "#tagModal" %>

$("<%= element %>").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

app/views/tags/_show_modal.js.erb
// モーダルを表示する。
$("#modalArea").find(".modal").modal('show')

app/views/tags/_tag.html.erb
<div data-model_name="<%= Tag.model_name.singular %>" data-id="<%= tag.id %>">
  <%= link_to edit_tag_path(tag), remote: true do %><div class="btn btn-secondary mr-1 mb-2"><%= tag.name %></div><% end %>
  <%= link_to tag_path(tag), method: :delete, remote: true, data: { confirm: "Deleting tag [#{tag.name}]. Are you sure?" } do %>
    <i class="fas fa-times text-danger"></i>
  <% end %>
</div>

app/views/tags/create.js.erb
// 値をクリアしてfocusする
$('.field input#tag_name').val("")
$('.field input#tag_name').focus();

// Rails @status => true 画面の書き換え : false モーダルを再度表示
<% if @status %>
$("#modalArea")
  .find("#tagIndex")
  .html('<%= j(render partial: "tags/tag", collection: current_user.tags.select(&:persisted?), as: :tag) %>')

<% else %>

// モーダルを閉じる処理
<%= render 'remove_modal' %>

// モーダルの書き換え
$("#modalArea").html("<%= j(render 'tags/form', tag: @tag) %>")

// モーダル表示
<%= render 'show_modal' %>
<% end %>

app/views/tags/destroy.js.erb
// モーダルの書き換え
$('[data-model_name="tag"]').filter('[data-id="<%= @tag.id %>"]').remove();

// すでに表示されているgoalsを書き換え
$('#goalsIndex').html('<%= j(render partial: "goals/goal", collection: current_user.goals, as: :goal) %>')

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/edit.js.erb
// モーダルを閉じる処理
<%= render 'remove_modal' %>

// モーダル追加
$("#modalArea").html(
  "<%= j(render 'edit_form', tag: @tag) %>"
);

// フォームにフォーカス
<%= render 'focus_modal' %>

// モーダル表示
<%= render 'show_modal' %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.user %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.js.erb
// モーダルを閉じる処理
<%= render 'remove_modal' %>

// モーダルの書き換え
$("#modalArea").html("<%= j(render 'form', tag: @tag) %>")

// フォームにフォーカス
<%= render 'focus_modal' %>

// モーダル表示
<%= render 'show_modal' %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @tag.user %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, url: [goal, todo], remote: true, html: {name: "todoForm", class: "p-2"} ) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      
      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_area :content, rows: 4 %>
  </div>
  
  <div class="actions text-right">
    <%= link_to "Close", new_goal_todo_path(goal), class: "btn btn-secondary", remote: true %>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/todos/_modal_form.html.erb
<div class="modal fade" id="goalModal" tabindex="-1" role="dialog" aria-labelledby="goalModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: todo, url: [goal, todo], remote: true, class: "") do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="goalModal"><%= "#{params[:action].camelize} #{todo.model_name.human}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if todo.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
              <ul>
                <% todo.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :content %>
            <%= form.text_area :content, rows: 5 %>
          </div>
          <div class="field">
            <%= form.collection_check_boxes :tag_ids, current_user.tags, :id, :name do |b| %>
              <%= b.label(class: "form-check") do %>
                <%= b.check_box(class: "form-check-input") %>
                <div class="btn btn-secondary" >
                  <%= b.text %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/_tag.html.erb
<div class="d-inline-block">
  <span class="badge badge-secondary mr-1"><%= tag.name %></span>
</div>

app/views/todos/_todo.html.erb
<div class="card mt-2 todo-card <%=" text-muted bg-light" if todo.done %>"
  data-model_name="<%= Todo.model_name.singular %>"
  data-goal_id="<%= todo.goal.id %>"
  data-id="<%= todo.id %>">
  <div class="card-body pr-1">
    <div class="card-text pr-4">
      <%= todo.done ? tag.del(){simple_format todo.content} : (simple_format todo.content) %>
    </div>
    <div class="btn-group position-absolute" style="top: 10px; right: 4px">
      <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v"></i>
      </button>
      <div class="dropdown-menu dropdown-menu-right text-middle">
        <%= form_with(model: todo, url: [todo.goal, todo], remote: true) do |form| %>
          <% if todo.done %>
            <%= form.hidden_field :done, value: false, readonly: true %>
            <%= form.submit "未完了", class: "dropdown-item text-success" %>
          <% else %>
            <%= form.hidden_field :done, value: true, readonly: true %>
            <%= form.submit "完了！", class: "dropdown-item text-success" %>
          <% end %>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "並びかえ", sort_goal_todo_path(todo.goal, todo), class: "dropdown-item", remote: true %>
        <%= link_to "編集", edit_goal_todo_path(todo.goal, todo), class: "dropdown-item", remote: true %>
        <%= link_to "削除",
            goal_todo_path(todo.goal, todo),
            method: :delete,
            class: "dropdown-item text-danger",
            remote: true, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <div class="card-text">
      <small class="text-muted">
        <%= todo.created_at.strftime('%Y/%m/%d') %>
      </small>
       <div>
        <%= render partial: "todos/tag", collection: todo.tags, as: :tag %>
      </div>
    </div>
  </div>
</div>

app/views/todos/destroy.js.erb
// 画面の書き換え
$('[data-model_name="todo"]').filter('[data-goal_id="<%= @goal.id %>"][data-id="<%= @todo.id %>"]').remove();